apiVersion: v1
kind: Service
metadata:
  name: kafkadedup-api
  namespace: kafkadedup
  labels:
    app.kubernetes.io/name: kafkadedup
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafkadedup
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
